name: Combine PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: github/combine-prs@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
